### ISSUE TITLE
Typo on one of your pages

### ISSUE THREAD

**Issue by yourpalnurav** [anandjoshi91/anandjoshi91.github.io#2]
anandjoshi91.github.io/_posts/2016/2016-10-16-Blogging-with-github-and-jekyll.md

just search for "quey" and replace it with "query"

 ;)

PS: Can I know how you custom designed google search bar...

**Comment by anandjoshi91** [comment]
Thanks @yourpalnurav 

For search bar check these files - 

[https://github.com/anandjoshi91/anandjoshi91.github.io/blob/master/pages/search/index.html](https://github.com/anandjoshi91/anandjoshi91.github.io/blob/master/pages/search/index.html)

[https://github.com/anandjoshi91/anandjoshi91.github.io/blob/master/_includes/searchform.html](https://github.com/anandjoshi91/anandjoshi91.github.io/blob/master/_includes/searchform.html)
